const LENGTH_BEG_FLAG = 2;
const LENGTH_TIME = 4;
const LENGTH_FILL = 6;
const LENGTH_DIRECTION = 1;

const POSITION_BEG_FLAG = 0; //起始位置
const POSITION_TIME = POSITION_BEG_FLAG + LENGTH_BEG_FLAG; // [2]Time位置  = 起始位置0 +  2([0]消息类型 + [1]消息长度)
const POSITION_FILL = POSITION_TIME + LENGTH_TIME; // [6]填充位置 = [2]Time位置 + Time长度[4]
const POSITION_DIRECTION = POSITION_FILL + LENGTH_FILL; // [12]方向位置 = [6]填充位置 + 填充长度[6]
const POSITION_MSG_BODY = POSITION_DIRECTION + LENGTH_DIRECTION;

module.exports = {
    LENGTH_BEG_FLAG,
    LENGTH_TIME,
    LENGTH_FILL,
    LENGTH_DIRECTION,
    POSITION_BEG_FLAG,
    POSITION_TIME,
    POSITION_FILL,
    POSITION_DIRECTION,
    POSITION_MSG_BODY,
};
